config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'posts#index'
  resources :posts
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :comments do
    resources :votes, only: [:create, :destroy]
  end
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  
  resources :export

  resources :notifications, only: [:create]

  mount ActionCable.server => '/cable'
end

app/models/comment.rb
# frozen_string_literal: true

# Model Comment
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, as: :notifiable
  validates :user, presence: true
  validates :content, presence: true
  validates :post, presence: true

  acts_as_votable
  acts_as_tree order: 'created_at ASC'
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# app/controllers/CommentsController
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:destroy]
  before_action :filter_comment, only: [:create]

  def create
    respond_to do |format|
      if @comment.save
        create_notification
        format.js
        format.html { redirect_back fallback_location: root_path }
      else
        format.html { render html: 'does not create comment !' }
      end
    end
  end

  def destroy
    @comment.descendants.each(&:destroy)
    @comment.destroy
    respond_to do |format|
      if @comment.save
        format.js
      else
        format.html { redirect_back fallback_location: root_path }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit :post_id, :user_id, :content
  end

  def set_comment
    @comment = Comment.find_by id: params[:id]
  end

  def filter_comment
    if params[:comment][:parent_id].to_i.positive?
      parent = Comment.find(params[:comment].delete(:parent_id))
      @comment = parent.children.build comment_params
    else
      @comment = Comment.new comment_params
    end
  end

  def create_notification
    object = @comment.parent || @comment.post
    Notification.create(
      recipient: object.user,
      user: current_user,
      action: 'comment', viewed: false, notifiable: @comment,
      post_id: @comment.post_id, comment_id: @comment_id
    )
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# CommentsHelper
module CommentsHelper
  def comments_tree_for(comments)
    safe_join(
      comments.map do |comment, _nested_comments|
        child = comment.children
        render(comment, post: comment.post, comment_new: Comment.new) +
          (tag.div(comments_tree_for(child), class: 'replies') if child)
      end
    )
  end
end

app/views/comments/_comment.html.erb
<div id="form-comment-<%= post.id %>-<%= comment.parent_id %>">
  <div class="row">
    <div class="col-md-1">
      <%= link_to gravatar_for(post.user, size: 40), user_confirmation_path(post.user) %>
    </div>
    <div class="col-md-11">
      <%= link_to (comment.user.name), user_path(comment.user_id) %>:
      <span class="timestamp">
        <%= comment.created_at %>
      </span><br/>
      <p><%= comment.content %><p>
      <%= link_to "delete", post_comment_path(post, comment),
                  method: :delete,
                  data: { confirm: t("posts.show.sure"), remote: true } %>
      <%= render "comments/vote_form", comment: comment %>
      <div class="col-md-11">
        <%= render "comments/comment_form", post: post, parent_id: comment.id,
                                            comment_new: Comment.new %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<% if user_signed_in? %>
  <span id="form-comment">
    <%= form_with(model: [post, comment_new], local: false) do |f| %>
      <%= f.hidden_field :parent_id, value: parent_id %>
      <%= f.hidden_field :post_id, value: post.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_area :content, placeholder: t("posts.show.compose"), required: true, class: "form-control add-comment" %>
      <%= f.submit "comment" %>
    <% end %>
  </span>
<% end %>

app/views/comments/_vote_form.html.erb
<div id="vote_form-comment<%= comment.id %>">
  <% if user_signed_in? %>
    <% if (current_user.voted_down_on? comment) || (!ActsAsVotable::Vote.where(voter_id: current_user, votable_id: comment.id).present?) %>
      <%= link_to comment_votes_path(comment), method: :post, remote: true do %>
        <span class="glyphicon glyphicon-heart-empty"></span>
      <% end %>
    <% else %>
      <%= link_to comment_vote_path(comment, 0), method: :delete, remote: true do %>
        <span class="glyphicon glyphicon-heart"></span>
      <% end %>
    <% end %>
  <% end %>
  <%= t "comments.show.like" %> <%= comment.get_upvotes.size %>
  <%= raw comment.votes_for.up.by_type(User).voters.map { |voter| link_to voter.email, "#" }.join(", ") %>
</div>

app/views/comments/create.js.erb
$('#form-comment-<%= @comment.post_id %>-<%= @comment.parent_id %>').before("<%= j render(@comment, post: @comment.post) %>");
$('#form-comment form textarea').val('');

app/views/comments/destroy.js.erb
$('#form-comment-<%= @comment.post_id %>-<%= @comment.parent_id %>').remove()