config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'posts#index'
  resources :posts
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :comments do
    resources :votes, only: [:create, :destroy]
  end
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  
  resources :export

  resources :notifications, only: [:create]

  mount ActionCable.server => '/cable'
end

app/models/notification.rb
# frozen_string_literal: true

# Model Notification
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :recipient, class_name: 'User'
  belongs_to :notifiable, polymorphic: true
  validates :user, presence: true
  validates :recipient, presence: true
  validates :notifiable, presence: true
  scope :get_of, ->(user) { where(recipient_id: user.id).reverse }
  scope :get_new, ->(user) { where(recipient_id: user.id, viewed: false) }

  after_commit -> { commit_callback }

  def commit_callback
    count = Notification.where(recipient_id: recipient.id, viewed: false).count
    NotificationRelayJob.perform_later(self, count)
    NotificationsMailer.send_notification(user).deliver_now
  end

  def self.update_viewed(user)
    noti = Notification.where(recipient_id: user.id, viewed: false)
    noti.map do |member|
      member.viewed = true
      member.save
    end
  end
end

app/controllers/notifications_controller.rb
# frozen_string_literal: true

# app/controllers/NotificationsController
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def create
    Notification.update_viewed(current_user)
    @notification = Notification.get_new(current_user)
    respond_to do |format|
      format.js
      format.html { redirect_back fallback_location: root_path }
    end
  end
end

app/helpers/notifications_helper.rb
# frozen_string_literal: true

# NotificationsHelper
module NotificationsHelper
end

app/views/notifications/_comment.html.erb
<div class="notifications-item">
  <%= link_to notification.notifiable do %>
    <div class="text">
      <%= gravatar_for notification.user, size: 30 %>
      <h4><%= notification.user.email %></h4>
      <p><%= notification.action %> comment your <%= notification.notifiable_type %></p>
    </div>
  <% end %>
</div>

app/views/notifications/_counter.html.erb
<div id="counter-open">   
      <div class="icon" id="bell"> <img src="https://i.imgur.com/AC7dgLA.png" alt=""> </div>
      <span id="notification-counter"><%= counter %></span>
</div>

app/views/notifications/_notification.html.erb
<%= render "notifications/#{notification.action}", notification: notification %>

app/views/notifications/_notification_center.html.erb
<ul class="notificator">
  <%= link_to(notifications_path(id: current_user.id), remote: true, method: :post) do %>
    <li id="open_notification">
      <%= render partial: "notifications/counter", locals: { counter: Notification.get_new(current_user).count } %>
    </li>
  <% end %>
  <div id="box" class="notifications">
      <ul id="notifications">
        <%= render partial: "notifications/notification", collection: notifications, as: :notification %>
      </ul>
  </div>
</ul>

<script>
  var down = false;
  $('#open_notification').click(function(e){
  var color = $(this).text();
  if(down){
    $('#box').css('height','0px');
    $('#box').css('opacity','0');
    down = false;
  }else{
    $('#box').css('height','auto');
    $('#box').css('opacity','1');
    down = true;
  }
});
</script>

app/views/notifications/_reaction.html.erb
<div class="notifications-item">
  <%= link_to notification.notifiable do %>
    <div class="text">
      <%= gravatar_for notification.user, size: 30 %>
      <h4><%= notification.user.email %></h4>
      <p><%= notification.action %> your <%= notification.notifiable_type %></p>
    </div>
  <% end %>
</div>