config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root    'posts#index'
  resources :posts
  resources :posts do
    resources :votes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  resources :comments do
    resources :votes, only: [:create, :destroy]
  end
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: :show
  
  resources :export

  resources :notifications, only: [:create]

  mount ActionCable.server => '/cable'
end

app/models/post.rb
# frozen_string_literal: true

# Model Post
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, as: :notifiable
  validates :content, length: { in: 5..100 }, presence: true
  validates :title, length: { minimum: 2 }, presence: true
  validates :user, presence: true
  acts_as_votable

  CSV_ATT = %w[content created_at].freeze

  scope :a_month_ago,
        lambda {
          where('created_at > ?', 1.month.ago).select(:content,
                                                      :created_at)
        }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

# app/controllers/PostsController
class PostsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @post = Post.new
    @comment = Comment.new
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = Post.new post_params
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html do
        redirect_to posts_url,
                    notice: 'Post was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit :title, :content, :user_id
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <% if user_signed_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>-">
  <%= link_to gravatar_for(post.user, size: 40), user_confirmation_path(post.user) %>
  <span class="user"><%= link_to post.user.name,
                                 user_confirmation_path(post.user) %></span></br>
  <span class="content"><%= post.content %></span></br>
  <%= image_tag post.image if post.image? %>
  <span class="timestamp"> Posted <%= time_ago_in_words(post.created_at) %> ago.
    <td><%= link_to "Show", post %></td>
    <% if current_user == post.user %>
    <%= link_to "delete", post, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %></br>
    <%= render "posts/vote_form", post: post %>
    Comments:</br>
    <div class="row">
      <%= render "comments/comment_form", post: post, parent_id: nil, comment_new: Comment.new %>
      <div class="col-md-11">
       <%= comments_tree_for post.comments.where(parent_id: nil).hash_tree(limit_depth: 2) %>
      </div>
    </div>
</li>

app/views/posts/_vote_form.html.erb
<div id="vote_form-post<%= post.id %>">
    <% if user_signed_in? %>
      <% if (current_user.voted_down_on? post) || (!ActsAsVotable::Vote.where(voter_id: current_user, votable_id: post.id).present?) %>
        <%= link_to post_votes_path(post), method: :post, remote: true do %>
          <span class="glyphicon glyphicon-heart-empty"></span>
        <% end %>
      <% else %>
        <%= link_to post_vote_path(post, 0), method: :delete, remote: true do %>
          <span class="glyphicon glyphicon-heart"></span>
        <% end %>
      <% end %>
    <% end %>
    <%= post.get_upvotes.size %> <%= t "posts.show.like" %>
    <%= raw post.votes_for.up.by_type(User).voters.map { |voter| link_to voter.email, "#" }.join(", ") %>
  </div>
  

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
</br>
<%= render "form", post: Post.new %>

<%= render @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= render "posts/vote_form", post: @post %>
<%= link_to "Edit", edit_post_path(@post) %> |
<%= link_to "Back", posts_path %>
<div class="row">
  <%= render "comments/comment_form", post: @post, parent_id: nil, comment_new: Comment.new %>
  <div class="col-md-11">
   <%= comments_tree_for @post.comments.where(parent_id: nil).hash_tree(limit_depth: 2) %>
  </div>
</div>